workflows:
  ios-release:
    name: iOS Build & Release
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ID: "your_app_store_connect_id"
      ios_signing:
        distribution_type: "app-store"
        bundle_identifier: "com.example.aliPashaGraph"
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS App
        script: |
          flutter build ios --release
      - name: Export IPA
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release archive -archivePath build/Runner.xcarchive
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        api_key_id: $APP_STORE_CONNECT_ID
        issuer_id: "your_issuer_id"
        key_content: $APP_STORE_CONNECT_KEY
        submit_to_testflight: true
